# Generated by Django 5.1.4 on 2025-04-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capixxer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosloja',
            old_name='produtos',
            new_name='produtos_gondola',
        ),
        migrations.AddField(
            model_name='dadosloja',
            name='produtos_nao_respondidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dadosloja',
            name='produtos_presente',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dadosloja',
            name='produtos_presente_reposto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dadosloja',
            name='produtos_respondidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dadosloja',
            name='produtos_ruptura',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dadosloja',
            name='total_produtos',
            field=models.IntegerField(default=0),
        ),
    ]
